// Code generated by "stringer -type=UIAControlType"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UIA_ButtonControlTypeId-50000]
	_ = x[UIA_CalendarControlTypeId-50001]
	_ = x[UIA_CheckBoxControlTypeId-50002]
	_ = x[UIA_ComboBoxControlTypeId-50003]
	_ = x[UIA_EditControlTypeId-50004]
	_ = x[UIA_HyperlinkControlTypeId-50005]
	_ = x[UIA_ImageControlTypeId-50006]
	_ = x[UIA_ListItemControlTypeId-50007]
	_ = x[UIA_ListControlTypeId-50008]
	_ = x[UIA_MenuControlTypeId-50009]
	_ = x[UIA_MenuBarControlTypeId-50010]
	_ = x[UIA_MenuItemControlTypeId-50011]
	_ = x[UIA_ProgressBarControlTypeId-50012]
	_ = x[UIA_RadioButtonControlTypeId-50013]
	_ = x[UIA_ScrollBarControlTypeId-50014]
	_ = x[UIA_SliderControlTypeId-50015]
	_ = x[UIA_SpinnerControlTypeId-50016]
	_ = x[UIA_StatusBarControlTypeId-50017]
	_ = x[UIA_TabControlTypeId-50018]
	_ = x[UIA_TabItemControlTypeId-50019]
	_ = x[UIA_TextControlTypeId-50020]
	_ = x[UIA_ToolBarControlTypeId-50021]
	_ = x[UIA_ToolTipControlTypeId-50022]
	_ = x[UIA_TreeControlTypeId-50023]
	_ = x[UIA_TreeItemControlTypeId-50024]
	_ = x[UIA_CustomControlTypeId-50025]
	_ = x[UIA_GroupControlTypeId-50026]
	_ = x[UIA_ThumbControlTypeId-50027]
	_ = x[UIA_DataGridControlTypeId-50028]
	_ = x[UIA_DataItemControlTypeId-50029]
	_ = x[UIA_DocumentControlTypeId-50030]
	_ = x[UIA_SplitButtonControlTypeId-50031]
	_ = x[UIA_WindowControlTypeId-50032]
	_ = x[UIA_PaneControlTypeId-50033]
	_ = x[UIA_HeaderControlTypeId-50034]
	_ = x[UIA_HeaderItemControlTypeId-50035]
	_ = x[UIA_TableControlTypeId-50036]
	_ = x[UIA_TitleBarControlTypeId-50037]
	_ = x[UIA_SeparatorControlTypeId-50038]
	_ = x[UIA_SemanticZoomControlTypeId-50039]
	_ = x[UIA_AppBarControlTypeId-50040]
}

const _UIAControlType_name = "UIA_ButtonControlTypeIdUIA_CalendarControlTypeIdUIA_CheckBoxControlTypeIdUIA_ComboBoxControlTypeIdUIA_EditControlTypeIdUIA_HyperlinkControlTypeIdUIA_ImageControlTypeIdUIA_ListItemControlTypeIdUIA_ListControlTypeIdUIA_MenuControlTypeIdUIA_MenuBarControlTypeIdUIA_MenuItemControlTypeIdUIA_ProgressBarControlTypeIdUIA_RadioButtonControlTypeIdUIA_ScrollBarControlTypeIdUIA_SliderControlTypeIdUIA_SpinnerControlTypeIdUIA_StatusBarControlTypeIdUIA_TabControlTypeIdUIA_TabItemControlTypeIdUIA_TextControlTypeIdUIA_ToolBarControlTypeIdUIA_ToolTipControlTypeIdUIA_TreeControlTypeIdUIA_TreeItemControlTypeIdUIA_CustomControlTypeIdUIA_GroupControlTypeIdUIA_ThumbControlTypeIdUIA_DataGridControlTypeIdUIA_DataItemControlTypeIdUIA_DocumentControlTypeIdUIA_SplitButtonControlTypeIdUIA_WindowControlTypeIdUIA_PaneControlTypeIdUIA_HeaderControlTypeIdUIA_HeaderItemControlTypeIdUIA_TableControlTypeIdUIA_TitleBarControlTypeIdUIA_SeparatorControlTypeIdUIA_SemanticZoomControlTypeIdUIA_AppBarControlTypeId"

var _UIAControlType_index = [...]uint16{0, 23, 48, 73, 98, 119, 145, 167, 192, 213, 234, 258, 283, 311, 339, 365, 388, 412, 438, 458, 482, 503, 527, 551, 572, 597, 620, 642, 664, 689, 714, 739, 767, 790, 811, 834, 861, 883, 908, 934, 963, 986}

func (i UIAControlType) String() string {
	i -= 50000
	if i < 0 || i >= UIAControlType(len(_UIAControlType_index)-1) {
		return "UIAControlType(" + strconv.FormatInt(int64(i+50000), 10) + ")"
	}
	return _UIAControlType_name[_UIAControlType_index[i]:_UIAControlType_index[i+1]]
}
