// Code generated by "stringer -type=UIAEvent"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UIA_ActiveTextPositionChangedEventId-20032]
	_ = x[UIA_AsyncContentLoadedEventId-20006]
	_ = x[UIA_AutomationFocusChangedEventId-20005]
	_ = x[UIA_AutomationPropertyChangedEventId-20004]
	_ = x[UIA_ChangesEventId-20034]
	_ = x[UIA_Drag_DragCancelEventId-20027]
	_ = x[UIA_Drag_DragCompleteEventId-20028]
	_ = x[UIA_Drag_DragStartEventId-20026]
	_ = x[UIA_DropTarget_DragEnterEventId-20029]
	_ = x[UIA_DropTarget_DragLeaveEventId-20030]
	_ = x[UIA_DropTarget_DroppedEventId-20031]
	_ = x[UIA_HostedFragmentRootsInvalidatedEventId-20025]
	_ = x[UIA_InputDiscardedEventId-20022]
	_ = x[UIA_InputReachedOtherElementEventId-20021]
	_ = x[UIA_InputReachedTargetEventId-20020]
	_ = x[UIA_Invoke_InvokedEventId-20009]
	_ = x[UIA_LayoutInvalidatedEventId-20008]
	_ = x[UIA_LiveRegionChangedEventId-20024]
	_ = x[UIA_MenuClosedEventId-20007]
	_ = x[UIA_MenuModeEndEventId-20019]
	_ = x[UIA_MenuModeStartEventId-20018]
	_ = x[UIA_MenuOpenedEventId-20003]
	_ = x[UIA_NotificationEventId-20035]
	_ = x[UIA_Selection_InvalidatedEventId-20013]
	_ = x[UIA_SelectionItem_ElementAddedToSelectionEventId-20010]
	_ = x[UIA_SelectionItem_ElementRemovedFromSelectionEventId-20011]
	_ = x[UIA_SelectionItem_ElementSelectedEventId-20012]
	_ = x[UIA_StructureChangedEventId-20002]
	_ = x[UIA_SystemAlertEventId-20023]
	_ = x[UIA_Text_TextChangedEventId-20015]
	_ = x[UIA_Text_TextSelectionChangedEventId-20014]
	_ = x[UIA_TextEdit_ConversionTargetChangedEventId-20033]
	_ = x[UIA_TextEdit_TextChangedEventId-20032]
	_ = x[UIA_ToolTipClosedEventId-20001]
	_ = x[UIA_ToolTipOpenedEventId-20000]
	_ = x[UIA_Window_WindowClosedEventId-20017]
	_ = x[UIA_Window_WindowOpenedEventId-20016]
}

const _UIAEvent_name = "UIA_ToolTipOpenedEventIdUIA_ToolTipClosedEventIdUIA_StructureChangedEventIdUIA_MenuOpenedEventIdUIA_AutomationPropertyChangedEventIdUIA_AutomationFocusChangedEventIdUIA_AsyncContentLoadedEventIdUIA_MenuClosedEventIdUIA_LayoutInvalidatedEventIdUIA_Invoke_InvokedEventIdUIA_SelectionItem_ElementAddedToSelectionEventIdUIA_SelectionItem_ElementRemovedFromSelectionEventIdUIA_SelectionItem_ElementSelectedEventIdUIA_Selection_InvalidatedEventIdUIA_Text_TextSelectionChangedEventIdUIA_Text_TextChangedEventIdUIA_Window_WindowOpenedEventIdUIA_Window_WindowClosedEventIdUIA_MenuModeStartEventIdUIA_MenuModeEndEventIdUIA_InputReachedTargetEventIdUIA_InputReachedOtherElementEventIdUIA_InputDiscardedEventIdUIA_SystemAlertEventIdUIA_LiveRegionChangedEventIdUIA_HostedFragmentRootsInvalidatedEventIdUIA_Drag_DragStartEventIdUIA_Drag_DragCancelEventIdUIA_Drag_DragCompleteEventIdUIA_DropTarget_DragEnterEventIdUIA_DropTarget_DragLeaveEventIdUIA_DropTarget_DroppedEventIdUIA_ActiveTextPositionChangedEventIdUIA_TextEdit_ConversionTargetChangedEventIdUIA_ChangesEventIdUIA_NotificationEventId"

var _UIAEvent_index = [...]uint16{0, 24, 48, 75, 96, 132, 165, 194, 215, 243, 268, 316, 368, 408, 440, 476, 503, 533, 563, 587, 609, 638, 673, 698, 720, 748, 789, 814, 840, 868, 899, 930, 959, 995, 1038, 1056, 1079}

func (i UIAEvent) String() string {
	i -= 20000
	if i < 0 || i >= UIAEvent(len(_UIAEvent_index)-1) {
		return "UIAEvent(" + strconv.FormatInt(int64(i+20000), 10) + ")"
	}
	return _UIAEvent_name[_UIAEvent_index[i]:_UIAEvent_index[i+1]]
}
